--INSERT NA TABELA USUARIOS
INSERT INTO USUARIOS (ID, NOME, DAT_NASCIMENTO, DAT_CRIACAO, DAT_ALTERACAO, DAT_EXCLUSAO, CRIADO_POR_USU_ID, ALTERADO_POR_USU_ID, EXCLUIDO_POR_USU_ID, IND_ATIVO)
VALUES (1, 'ALAN LOPES', '2000-02-25', GETDATE(), NULL, NULL, 1, NULL, NULL, 1)

INSERT INTO USUARIOS(ID, NOME, DAT_NASCIMENTO, DAT_CRIACAO, DAT_ALTERACAO, DAT_EXCLUSAO, CRIADO_POR_USU_ID, ALTERADO_POR_USU_ID, EXCLUIDO_POR_USU_ID, IND_ATIVO)
VALUES (2, 'HELEN', '2008-05-23', GETDATE(), NULL, NULL, 1, NULL, NULL, 1)

--INSERT NA TABELA PRODUTOS
INSERT INTO PRODUTOS (ID, NOME, DATA_ALTERACAO,	DATA_CRIACAO,	DATA_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID, IND_ATIVO)
VALUES (9, 'CALCULADORA', GETDATE(), NULL, NULL, 1, NULL, NULL, 1)

INSERT INTO PRODUTOS (ID, NOME, DATA_ALTERACAO,	DATA_CRIACAO,	DATA_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID, IND_ATIVO)
VALUES (7, 'LIVROS', GETDATE(), NULL, NULL, 2, NULL, NULL, 1)

--INSERT NA TABELA VENDAS
INSERT INTO VENDAS (ID,	DAT_CRIACAO,	DAT_ALTERACAO,	DAT_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID,	IND_ATIVO)
VALUES (1111, GETDATE(), NULL, NULL, 1, NULL, NULL, 1)

INSERT INTO VENDAS (ID,	DAT_CRIACAO,	DAT_ALTERACAO,	DAT_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID,	IND_ATIVO)
VALUES (1112, GETDATE(), NULL, NULL, 2, NULL, NULL, 1)

--INSERT NA TABELA VENDAS_PRODUTOS
INSERT INTO VENDAS_PRODUTOS (ID,	ID_VENDA,	ID_PRODUTO,	VALOR,	DESCONTO,	VALOR_FINAL,	DAT_CRIACAO,	DAT_ALTERACAO,	DAT_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID,	IND_ATIVO)
VALUES (598, 1010, 1, 1200.65, 150.15,  1050.5, GETDATE(), NULL, NULL, 1, NULL, NULL, 1 )

INSERT INTO VENDAS_PRODUTOS (ID,	ID_VENDA,	ID_PRODUTO,	VALOR,	DESCONTO,	VALOR_FINAL,	DAT_CRIACAO,	DAT_ALTERACAO,	DAT_EXCLUSAO,	CRIADO_POR_USU_ID,	ALTERADO_POR_USU_ID,	EXCLUIDO_POR_USU_ID,	IND_ATIVO)
VALUES (597, 1011, 12, 900, 50,  850, GETDATE(), NULL, NULL, 2, NULL, NULL, 1 )