USE SysMap
GO
CREATE TABLE VENDAS_PRODUTOS(
ID INT NOT NULL PRIMARY KEY,
ID_VENDA INT NULL,
ID_PRODUTO INT  NULL,
VALOR INT  NULL,
DESCONTO INT NULL,
VALOR_FINAL INT NULL,
DAT_CRIACAO DATETIME NOT NULL,
DAT_ALTERACAO DATETIME NULL,
DAT_EXCLUSAO DATETIME NULL,
CRIADO_POR_USU_ID INT NULL,
ALTERADO_POR_USU_ID INT NULL,
EXCLUIDO_POR_USU_ID INT NULL,
IND_ATIVO BIT NULL,
CONSTRAINT FK_VENDAS_PRODUTOS FOREIGN KEY (ID_VENDA) REFERENCES VENDAS (ID),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID)
);