USE SysMap
GO
CREATE TABLE PRODUTOS(
ID INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NULL,
VALOR INT NULL,
DATA_CRIACAO DATETIME NULL,
DATA_ALTERACAO DATETIME NULL,
DATA_EXCLUSAO DATETIME NULL,
CRIADO_POR_USU_ID INT  NOT NULL,
ALTERADO_POR_USU_ID INT  NULL,
EXCLUIDO_POR_USU_ID INT  NULL,
IND_ATIVO BIT NULL
);


