USE SysMap
GO
CREATE TABLE VENDAS(
ID INT NOT NULL PRIMARY KEY,
DAT_CRIACAO DATETIME NULL,DAT_ALTERACAO DATETIME NULL,DAT_EXCLUSAO DATETIME NULL,CRIADO_POR_USU_ID INT NULL,ALTERADO_POR_USU_ID INT NULL,EXCLUIDO_POR_USU_ID INT NULL,IND_ATIVO BIT NULL
);